[package]
name = "cuda-binding"
version = "0.1.0"
edition = "2024"

[dependencies]
cudarc = { version = "0.16", features = ["cuda-version-from-build-system"] }
derive_more = { version = "2", features = ["from", "display"] }
