[package]
name = "tools"
version = "0.1.3"
edition = "2021"

[dependencies]
experimenter = { version = "0.1.3", path = "../experimenter" }
anyhow = "1.0.86"
glob = "0.3.1"
serde_json = "1.0.124"

[[bin]]
name = "csv2bin"
path = "src/csv2bin.rs"
